SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Cereal Carnage"

INSTRUCTIONS_PAGE_0 = 0
INSTRUCTIONS_PAGE_1 = 1
GAME_RUNNING = 2
GAME_OVER = 3
WIN = 4

ENNEMY0_COUNT = 5
RESPAWN_TIME = 5

FIRE_RATE = 90
MOVEMENT_SPEED = 7
BULLET_SPEED = 6
BULLET1_SPEED = 6

SPRITE_SCALING_PLAYER = 0.9
SPRITE_SCALING_ENNEMY0 = 0.65
SPRITE_SCALING_LOOP = 0.3
SPRITE_SCALING_LASERRED = 0.5

LASER_SKIN_ENNEMY0 = "images/laserred.png"
LASER_SKIN_PLAYER = "images/loopblue.png"
LASER_SKIN_PLAYER1 = "images/looppurple.png"
LASER_SKIN_PLAYER2 = "images/loopyellow.png"
LASER_SKIN_PLAYER3 = "images/loopred.png"
LASER_SKIN_PLAYER4 = "images/loopgreen.png"

PICK = [LASER_SKIN_PLAYER,LASER_SKIN_PLAYER1,LASER_SKIN_PLAYER2,LASER_SKIN_PLAYER3,LASER_SKIN_PLAYER4]

BACKGROUND0 = "images/floortorch.png"